name: CI
on: push

jobs:
  deploy-website:
    environment: Production
    runs-on: ubuntu-latest

    steps:
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
      - name: Install Go
        uses: actions/setup-go@v2
      - name: Install protoc-gen-doc
        run: go get -u github.com/pseudomuto/protoc-gen-doc/cmd/protoc-gen-doc
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Generate protobuf docs
        run: protoc --doc_out="website/docs/protobufs" --doc_opt="./website/protobuf.tmpl,api.md" --proto_path="protobufs" protobufs/*.proto
      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: "--prod"
          vercel-org-id: ${{ secrets.ORG_ID}}
          vercel-project-id: ${{ secrets.PROJECT_ID}}
          working-directory: /
