name: "Update protobufs"
on: workflow_dispatch

jobs:
  update-protobufs:
    environment: Production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}  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
          submodules: true

      - name: Update Submodule
        run: |
          git pull --recurse-submodules
          git submodule update --remote --recursive

      - name: Commit update
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'bot@noreply.github.com'
          git commit -m "Update protobuf submodule" && git push || echo "No changes to commit"
